/**
 * API Route: Generate QR Code for Table
 */

import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { tables } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import QRCode from "qrcode";
import { requireTenantContext } from "@/lib/dashboard-auth";

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ tableId: string }> }
) {
  try {
    // Stage C3: this route previously had NO auth — any tableId could be
    // regenerated by anyone. Resolve the caller's tenant and verify ownership.
    const ctx = await requireTenantContext();
    if (!ctx.ok) {
      return NextResponse.json({ error: ctx.error }, { status: ctx.status });
    }

    const { tableId } = await params;

    // Get the table
    const table = await db.query.tables.findFirst({
      where: eq(tables.id, tableId),
    });

    // Ownership check: the table must belong to the caller's resolved location.
    // Return 404 (not 403) for a foreign table so we don't leak its existence.
    if (!table || table.locationId !== ctx.location.id) {
      return NextResponse.json({ error: "Table not found" }, { status: 404 });
    }

    // Generate QR code
    const paymentUrl = `${process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}/pay/${tableId}`;
    
    const qrCodeDataUrl = await QRCode.toDataURL(paymentUrl, {
      width: 400,
      margin: 2,
      color: {
        dark: "#000000",
        light: "#FFFFFF",
      },
    });

    // Update table with QR code
    await db
      .update(tables)
      .set({ qrCodeUrl: qrCodeDataUrl })
      .where(eq(tables.id, tableId));

    return NextResponse.json({ qrCodeUrl: qrCodeDataUrl });
  } catch (error) {
    console.error("Error generating QR code:", error);
    return NextResponse.json(
      { error: "Failed to generate QR code" },
      { status: 500 }
    );
  }
}
